### ISSUE TITLE
Request to create new tag releases for new updates

### ISSUE THREAD

**Issue by daniruiz** [ProcessusT/HEKATOMB#21]
Hello, I'm the maintainer of the hekatomb package in Kali Linux.
I'm wondering if it was possible to change a bit the new version release workflow, adding a new git tag with the release version. That way it's much easier for us to track new versions of the package and automate the updates.

**Comment by ProcessusT** [comment]
Is it good like this ?
https://github.com/ProcessusT/HEKATOMB/releases/tag/1.5.2

**Comment by daniruiz** [comment]
Yes! that's perfect ;) thank you
